[project]
name = "smithy-json"
dynamic = ["version"]
requires-python = ">=3.12"
authors = [
  {name = "Amazon Web Services"},
]
description = "JSON serialization and deserialization support for Smithy tooling."
readme = "README.md"
license = {text = "Apache License 2.0"}
keywords = ["smithy", "sdk", "json"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Natural Language :: English",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries"
]
dependencies = [
    "ijson>=3.3.0",
    "smithy-core~=0.1.0",
]

[project.urls]
"Changelog" = "https://github.com/smithy-lang/smithy-python/blob/develop/packages/smithy-json/CHANGELOG.md"
"Code" = "https://github.com/smithy-lang/smithy-python/blob/develop/packages/smithy-json/"
"Issue tracker" = "https://github.com/smithy-lang/smithy-python/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/smithy_json/__init__.py"

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.ruff]
src = ["src"]
