[project]
name = "smithy-aws-core"
version = "0.0.2"
description = "Core Smithy components for AWS services and protocols."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "smithy-core",
    "smithy-http",
    "aws-sdk-signers"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.ruff]
src = ["src"]
