[project]
name = "smithy-aws-core"
dynamic = ["version"]
requires-python = ">=3.12"
authors = [
  {name = "Amazon Web Services"},
]
description = "Core Smithy components for AWS services and protocols."
readme = "README.md"
license = {text = "Apache License 2.0"}
keywords = ["aws", "sdk", "amazon", "smithy"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Natural Language :: English",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries"
]
dependencies = [
    "smithy-core~=0.1.0",
    "smithy-http~=0.1.0",
    "aws-sdk-signers~=0.1.0"
]

[project.urls]
"Changelog" = "https://github.com/smithy-lang/smithy-python/blob/develop/packages/smithy-aws-core/CHANGELOG.md"
"Code" = "https://github.com/smithy-lang/smithy-python/blob/develop/packages/smithy-aws-core/"
"Issue tracker" = "https://github.com/smithy-lang/smithy-python/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/smithy_aws_core/__init__.py"

[project.optional-dependencies]
eventstream = [
    "smithy-aws-event-stream~=0.1.0"
]
json = [
    "smithy-json~=0.1.0"
]

[tool.hatch.build]
exclude = [
  "tests",
]

[tool.ruff]
src = ["src"]
