name: CI

on:
    pull_request:
    push:
        branches:
          - develop
          - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up JDK 17
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true

      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.8.2

      - name: Setup workspace
        run: |
          make install

      - name: Check python packages
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          make check-py

      - name: Test python packages
        run: |
          make test-py

      - name: Build python packages
        run: |
          make build-py

      - name: Build (and test) java packages
        run: |
          make build-java

      - name: Run protocol tests
        run: |
          make test-protocols
