name: CI

on:
    pull_request:
    push:
        branches:
          - develop
          - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true

      - name: Setup workspace
        run: |
          make install

      - name: Check python packages
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          make check-py

      - name: Test python packages
        run: |
          make test-py

      - name: Build python packages
        run: |
          make build-py

      - name: Build (and test) java packages
        run: |
          make build-java

      - name: Run protocol tests
        run: |
          make test-protocols
