name: CI

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          ./pants --no-dynamic-ui test --use-coverage ::
      - name: Upload coverage
        if: matrix.python-version == 3.10
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./dist/coverage/python/coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true

  test-codegen:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    name: Codegen Java 17 / Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Download Coretto 17 JDK
        run: |
          download_url="https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Coretto 17 JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: 17
          architecture: x64

      - name: clean and build without python
        run: cd codegen && ./gradlew clean build -Plog-tests

      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install smithy-python
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade .

      - name: clean and build without formatting/linting installed
        run: cd codegen && ./gradlew clean build -Plog-tests

      - name: Install black
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade black

      - name: clean and build without linting installed
        run: cd codegen && ./gradlew clean build -Plog-tests

      - name: Install mypy
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade mypy

      - name: clean and build with all optional tools installed
        run: cd codegen && ./gradlew clean build -Plog-tests
