name: Protocol Tests

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  protocol-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: RestJson1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Corretto 17 JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Set up Python for protocol tests - 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          pants-ci-config: pants.ci.toml

      - name: Run protocol tests
        run: make test-protocols
