name: Update Gradle Wrapper
# Needed because dependabot doesn't support updating the gradle wrapper
# see: https://github.com/dependabot/dependabot-core/issues/2223

on:
  schedule:
    # Run at midnight (UTC) every wednesday
    - cron: "0 0 * * 3"

permissions:
  contents: read

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    permissions:
        # allow job to open a pull request with changes
        pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5
        with:
          paths: codegen/**
